### ISSUE TITLE
psrqpy doesn't load psrcat.db (the sqlite version) even when it's placed in the cache dir

### ISSUE THREAD

**Issue by PaulHancock** [mattpitkin/psrqpy#128]
If I download/extract the `psrcat.db` from the latest version of the [ATNF catalog](https://www.atnf.csiro.au/research/pulsar/psrcat/download.html) (v2.0.0) and place it in the `CACHEDIR` it isn't found by psrqpy when I call `QueryATNF()`.

However, if I use `QueryATNF(loadfromdb=psrqpy.CACHEDIR+'psrcat.db')` it works just fine.

I suspect the reason is that the change in "db" format from a text file to an SQLite db is confusing the file reader.

**Comment by mattpitkin** [comment]
Hi @PaulHancock, thanks for reporting this. I had noticed this too. I'm not quite sure what the issue is as the downloadable tarball has the same information in and the `psrcat.db` file is the same format (apparently George has to produce this file from the SQL database for backwards compatibility). I'll take a look into the issue.

**Comment by mattpitkin** [comment]
The issue with the latest version of the `psrcat_pkg.tar.gz` tarball is that the archive stores the directories with a leading "`./`", which psrqpy does not expect. I've asked George if this discrepancy can be fixed, but if not I'll put a workaround in psrqpy and issue a new release.

**Comment by mattpitkin** [comment]
@PaulHancock The `psrcat_pkg.tar.gz` tarball from the catalogue download page has now been fixed, so psrqpy should work for v2.0.0 of the catalogue. Thanks again for reporting this.
