### ISSUE TITLE
Version downloads

### ISSUE THREAD

**Issue by astrophysically** [mattpitkin/psrqpy#94]
I was wondering if psrqpy could allow for direct version specification in QueryATNF methods. For example, today they v1.66 update broke the query due to mistakes in the database (not the first time this has happened). It would be nice to be able to just ask for v1.65 as stored here: https://www.atnf.csiro.au/research/pulsar/psrcat/download.html

**Comment by mattpitkin** [comment]
Hi @astrophysically, yes, being able to use specific version would indeed by nice. Previously (at least when I last thought about this and looked) they didn't seem to have the older tarballs publicly available, but now that they are I can definitely add this functionality

**Comment by mattpitkin** [comment]
I've just added a new release (v1.1.6) which has this feature.

**Comment by mattpitkin** [comment]
Just for the record, looking at the database file for the current (v1.66) version, I think the issue comes from `DIST_A` not being defined correctly for J1953+1846B, J1953+1846C and J1953+1846D. There is a paper reference in place of the `DIST_A` value, which I think should instead be 4.0 to be consistent with J1953+1846A. Pulsars J1748-2446ac and J1748-2446D also have the `DIST_A` value defined twice with different values.

**Comment by mattpitkin** [comment]
I've submitted this on the catalogue feedback page, so hopefully it'll be fixed soon.

**Comment by mattpitkin** [comment]
The v1.66 catalogue version has now been fixed, so it can be parsed by psrqpy
